---
version: '2'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    env_file:
      - .env

  heartbeat:
    extends: base
    command: bin/web
    ports:
      - '4567:4567'
    depends_on:
      - postgres

  talkdesk_consumer:
    extends: base
    command: bin/talkdesk_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres

  routing_consumer:
    extends: base
    command: bin/routing_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres

  postgres:
    image: postgres
    ports:
      - '5432:5432'
