---
version: '2.1'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    env_file:
      - .env

  heartbeat_seed:
    extends: base
    command: bin/db/create_schema
    depends_on:
      - postgres

  heartbeat:
    extends: base
    command: bin/web
    ports:
      - '4567:4567'
    depends_on:
      - postgres

  talkdesk_consumer:
    extends: base
    command: bin/talkdesk_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres
      - rabbitmq
    restart: on-failure

  routing_consumer:
    extends: base
    command: bin/routing_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres
      - rabbitmq
    restart: on-failure

  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: heartbeat_monitor
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

