---
version: '2'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    environment:
      - ROUTING_EVENTS_AMQP_URL=amqp://td-qa:aisiuPangohye6wae3EeP5euw0phu1ahlohwahziph5aepeiph@qa-rabbitmq.talkdeskdev.com:5672/talkdesk-qa
      - TALKDESK_EVENTS_AMQP_URL=amqp://td-qa:aisiuPangohye6wae3EeP5euw0phu1ahlohwahziph5aepeiph@qa-rabbitmq.talkdeskdev.com:5672/talkdesk-qa
      - POSTGRES_URL=postgresql://postgres@postgres:5432/postgres

  heartbeat:
    extends: base
    command: bin/web
    ports:
      - '4567:4567'
    depends_on:
      - postgres

  talkdesk_consumer:
    extends: base
    command: bin/talkdesk_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres

  routing_consumer:
    extends: base
    command: bin/routing_consumer
    stdin_open: true
    tty: true
    depends_on:
      - heartbeat
      - postgres

  postgres:
    image: postgres
    ports:
      - '5432:5432'
